### ISSUE TITLE
Unsupported path type

### ISSUE THREAD

**Issue by fineless71** [bajrangCoder/acode-plugin-acodex#16]
When I press the folder icon it says `unsupported path type`. What type of paths are allowed?

**Comment by bajrangCoder** [comment]
Can you share a screenshot of Editor?
Currently Internal storage and Termux Storage paths are allowed.

**Comment by fineless71** [comment]
The path is in internal storage
![Screenshot_20230615-023954](https://github.com/bajrangCoder/acode-plugin-acodex/assets/118756680/56a1c11c-f1dc-4f1d-b77e-3e38c2cfdc29)

Here's a screenshot from my file manager showing it is in internal storage:
![Screenshot_20230615-024315](https://github.com/bajrangCoder/acode-plugin-acodex/assets/118756680/f03afd4d-5699-455b-9acd-057e9153aae8)

**Comment by bajrangCoder** [comment]
It's detect Internal Storage file via this in starting: `file:///storage/emulated/0/` , So please check file path in Acode file info and also share it.

**Comment by fineless71** [comment]
I'm not sure how to open that menu, sorry. Will the image below help? If not, how do I open that?
![Screenshot_20230615-030833](https://github.com/bajrangCoder/acode-plugin-acodex/assets/118756680/7799263a-4e21-4f6d-8b6a-9e242ff3b2b4)

**Comment by fineless71** [comment]
I found out how to open it, here you go:
![Screenshot_20230615-031050](https://github.com/bajrangCoder/acode-plugin-acodex/assets/118756680/9ebd4a43-bd88-43bd-8fc2-fec7c3852329)

**Comment by bajrangCoder** [comment]
I guess you have Added this `dev` project folder using **Add Path** feature of Acode that's why it doesn't give actual path to **AcodeX plugin** and it returns unsupported path message.
For example you check given video:

https://github.com/bajrangCoder/acode-plugin-acodex/assets/71929976/071c72fb-639c-4f14-8663-6d2bcf962f84

To fix it just open file directly from internal storage, don't use **Add Path** storage, then it will work with `AcodeX plugin`

**Comment by fineless71** [comment]
I don't have an option to open internal storage, both with and without add path. I will wait for the next update, thanks.
https://github.com/bajrangCoder/acode-plugin-acodex/assets/118756680/0120b0d0-852b-4a47-a924-0bdc23e93b9e

**Comment by bajrangCoder** [comment]
Thanks for Waiting but don't worry today I will provide update ❤️

**Comment by bajrangCoder** [comment]
Please checkout latest version, this issue is fixed.

**Comment by fineless71** [comment]
I'm still getting this issue
![Screenshot_20230617-010743](https://github.com/bajrangCoder/acode-plugin-acodex/assets/118756680/501bef34-4b84-4fe5-8ad9-01639304bb16)

**Comment by fineless71** [comment]
I tried importing the path another way and I get this issue instead
![Screenshot_20230617-010957](https://github.com/bajrangCoder/acode-plugin-acodex/assets/118756680/e191671a-db89-4883-85b9-b14e855e0cbf)

**Comment by bajrangCoder** [comment]
I'm seeing this(`Internal storage abc::8254-36A8:collection/projects/libs/dev/main.c`) type of path first time. This plugin can't detect these type of file paths. I will research on it.

It given permission error because termux doesn't have access to your internal storage without your permission, you can enable it by running `termux-setup-storage` in termux. Then there will be no any permission error.

I will recommend you to use `Add path` feature. If still you get `unsupported path` error then please provide your device information. And don't use this feature, instead do it manually in AcodeX terminal by using `cd`.
For eg:
```
~ $ cd <your folder location>
```

**Comment by fineless71** [comment]
Thanks for the work you do on this plugin. The button works correctly when I import the path normally and give Termux permissions, thanks. So I will import my paths the normal way, but in case you want to know how I added that other path, here is a video:


https://github.com/bajrangCoder/acode-plugin-acodex/assets/118756680/1c746855-650e-4616-a132-a79b6e1e0e95

**Comment by bajrangCoder** [comment]
Ok , now I will try to fix this issue!
