### ISSUE TITLE
Issue on installation

### ISSUE THREAD

**Issue by HavyasRai** [bajrangCoder/acode-plugin-acodex#2]
Hello sir.....
I liked your work for acodeX....
But,while installing the same on the termux it shows that the "acodeX-server command not found" ....plz reply sir...

**Comment by bajrangCoder** [comment]
Please share screenshot and provide more about the problem. And also mention you Android version

**Comment by HavyasRai** [comment]
![Screenshot_2023-02-25-09-51-41-863_com termux](https://user-images.githubusercontent.com/113080389/221337017-d205ca47-2c33-4922-90d5-55aab6dfa546.jpg)
Hello...
I copied the link from your profile of the acodeX- server plugin and pasted the same to termux....after running it shows that the acodeX-server command not found.....MY DEVICE IS REDMI 8A ANDROID 10

**Comment by bajrangCoder** [comment]
You have downloaded termux from Play Store??

If yes , Then you need to install Termux from its GitHub repo or F-droid because Termux is deprecated on Play Store.

If no, Try below methods.
You can try by breaking the command in two parts:
```bash
curl -sL https://raw.githubusercontent.com/bajrangCoder/acode-plugin-acodex/main/installServer.sh | bash
```
And after installation you can run server via `acodeX-server`
Or you can also check that `curl` is installed on your termux or not by: `curl --version`
If above method doesn't works for you then you can manually download the [installServer.sh](https://github.com/bajrangCoder/acode-plugin-acodex/blob/main/installServer.sh) and move downloaded file into termux home directory and then run `bash installServer.sh`

Try these methods and let me know if these worked or not.

**Comment by HavyasRai** [comment]
Yes....this helped me.
i installed it by deviding the command into two parts and it worked...!!.
Thank you for your respond......

**Comment by KP-Boateng** [comment]
I followed all steps but still
![Screenshot_20230612-040912_Termux](https://github.com/bajrangCoder/acode-plugin-acodex/assets/72589907/c39a8b96-14a2-41e9-bcec-9b63927c5fa0)

**Comment by ar-xing** [comment]
我在中国怎么下载阿

**Comment by bajrangCoder** [comment]
> 我在中国怎么下载阿

Please use English!

Btw you can install it inside Acode and Acode is available on play Store or f-droid, etc

**Comment by ar-xing** [comment]
chine

**Comment by ar-xing** [comment]
Hello, I'm in China, Google is out of China, what to do

**Comment by ar-xing** [comment]
Hello I'm in China, Google services are out of China, what to do

**Comment by bajrangCoder** [comment]
> Hello I'm in China, Google services are out of China, what to do

Then download Acode from it's official telegram group or discord group or f-droid and termux can be installed from f-droid, as termux is deprecated on Google

**Comment by ar-xing** [comment]
f-droid No, is there anything else?

**Comment by bajrangCoder** [comment]
> f-droid No, is there anything else?

Then download Termux from their official [GitHub release](https://github.com/termux/termux-app/releases/tag/v0.118.0) and Acode from it's official telegram group or discord server

**Comment by ar-xing** [comment]
ok
