### ISSUE TITLE
Error installing acodex-server

### ISSUE THREAD

**Issue by Imlalit-007** [bajrangCoder/acode-plugin-acodex#56]
**acodex-server package is not installing**
when I try to install it I got some errors.

This is the error in my termux terminal

~ $ npm install -g acodex-server
[##################] / reify:hono: timing rei
> node-pty@1.0.0 install
> node-gyp rebuild

gyp info it worked if it ends with okming rei
gyp info using node-gyp@10.0.1
gyp info using node@21.6.2 | android | arm64
gyp info find Python using Python version 3.11.8 found at "/data/data/com.termux/files/usr/bin/python3"
[##################] / reify:hono: timing rei
gyp info spawn /data/data/com.termux/files/usr/bin/python3
gyp info spawn args [
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/home/.cache/node-gyp/21.6.2/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/21.6.2',
gyp info spawn args '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/21.6.2/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable android_ndk_path in binding.gyp while trying to load binding.gyp
gyp ERR! configure error ify:hono: timing rei
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 4.19.191+
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty
gyp ERR! node -v v21.6.2
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-02-24T09_05_24_586Z-debug-0.log
~ $

please fix it as soon as possible

**Comment by bajrangCoder** [comment]
Currently I don't have any working solution

But very soon I will come up with a solution ☹️

Stay tuned! Sorry for Inconvenience 😔

**Comment by bajrangCoder** [comment]
For now you can try Userland instead of termux

**Comment by bajrangCoder** [comment]
https://github.com/termux/termux-app/issues/3858

**Comment by harsha1-2-3** [comment]
I also have same issue
![Screenshot_2024-02-24-22-37-32-98_84d3000e3f4017145260f7618db1d683](https://github.com/bajrangCoder/acode-plugin-acodex/assets/157681158/6e351fc4-8c91-4952-815a-5cfd6ef27edf)

Please provide step by step solution i tried lot of ways by searching about this but never worked

**Comment by KJoo** [comment]
Having problems downloading too ans its my first time :/ honestly thought I should just Uninstall acode all together cause there are better apps that I can quickly compile without going through all this

**Comment by bajrangCoder** [comment]
@harsha1-2-3  @Imlalit-007 
You can try the following temporary solution:

- Open Termux
- Create a folder in termux home directory (by default termux always opens in its home directory),  using : `mkdir .gyp`
- Create a file inside .gyp folder , name: `include.gypi`
- and paste the following code inside the include.gypi file:

```
{
 'variables': {
  'android_ndk_path': ''
 }
}
```
- after that you can install acodex-server easily without any problem with the official script mentioned in readme

Or use following command to fix the issue:

```bash
cd $HOME && mkdir -p .gyp && echo "{'variables': {'android_ndk_path': ''}}" > .gyp/include.gypi
```

Then install acodex-server :)

**Comment by harsha1-2-3** [comment]
Thanks Bro package installed with out errors.
But while trying to start the server with **acodex-server**  **acodeX-server**  **axs**  it's showing this error 
![Screenshot_2024-02-29-16-54-49-40_84d3000e3f4017145260f7618db1d683](https://github.com/bajrangCoder/acode-plugin-acodex/assets/157681158/e1f1cb88-fe73-4989-be63-e36fd630c32b)
What happened bro please provide step by step solution to resolve issue....

**Comment by bajrangCoder** [comment]
Just update the server,
USING :
```bash
npm update -g acodex-server
```

**Comment by webmaster-exit-1** [comment]
Works for me, ty.
![Screenshot_2024-04-12-12-46-45-26_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/bajrangCoder/acode-plugin-acodex/assets/98633966/69c2b4d3-866f-4af3-94f4-2ba02c7d608a)

**Comment by webmaster-exit-1** [comment]
Question, do we add the server in the settings.json? ![Screenshot_2024-04-12-12-49-38-20_a2cf8efcdd42a8e6f7906303f104fb67.jpg](https://github.com/bajrangCoder/acode-plugin-acodex/assets/98633966/db02e2f4-c748-4bbd-993f-b67dd2f0e24a)

**Comment by bloodykheeng** [comment]
Thanks! You've shared a very detailed process that others in the Termux/Android/AcodeX community will find helpful.

Here's a complete, clean summary of your installation steps, errors, and working fix, formatted for GitHub or documentation.


---

✅ Installing acodeX-server / axs in Termux (Working Fix)

This guide walks you through installing the [acodeX-server](https://github.com/bajrangCoder/acode-plugin-acodex) backend on Termux, resolving common errors like read-only filesystem, node-gyp issues, and command not found.


---

🔧 Initial Setup Attempt (Manual Fix)

If you start with:

cd $HOME && mkdir -p .gyp && echo "{'variables': {'android_ndk_path': ''}}" > .gyp/include.gypi

You may still get build errors, such as:

gyp ERR! command "/data/data/com.termux/files/usr/bin/node" ...
gyp ERR! cwd .../node_modules/node-pty
gyp ERR! node -v v24.4.0
npm ERR! code 1

> These are caused by incompatible native module builds (node-pty) and Android/Termux architecture.




---

🧪 Attempting the Global NPM Install

npm install -g acodex-server

You may see:

acodeX-server: command not found

Or failed builds due to node-gyp.


---

✅ Working Method (No node-gyp Required)

Thanks to the updated installer, this is now fixed!

🥇 1. Run the updated installer

curl -sL https://raw.githubusercontent.com/bajrangCoder/acode-plugin-acodex/main/installServer.sh | bash

> This downloads a precompiled binary axs-android-arm64 to your $HOME.



You may see errors like:

mv: inter-device move failed: 'axs-android-arm64' to '/bin/axs'; Read-only file system

That’s expected in Termux — /bin is read-only.


---

🛠️ 2. Manual Fix for Termux

Move the downloaded binary to a writable directory and add it to your PATH:

mkdir -p $HOME/bin
mv $HOME/axs-android-arm64 $HOME/bin/axs
chmod +x $HOME/bin/axs
echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
source ~/.bashrc

> Use .zshrc instead of .bashrc if you're using zsh.




---

✅ 3. Run the server

axs

Expected output:

CLI/Server backend for AcodeX Acode plugin
Usage: axs [OPTIONS] [COMMAND]
Commands:
  update   Update axs server
  help     Print this message
Options:
  -p, --port <PORT>   Port to start the server [default: 8767]
  -i, --ip            Start on LAN IP
  -h, --help


---

✅ You're Done!

You can now connect Acode's plugin to the running axs server in Termux.
If you need the GUI interface, run:

axs --gui

---
